# Generated by Django 5.2.6 on 2025-10-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(help_text='CAR ID', max_length=20)),
                ('carname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('model', models.IntegerField()),
            ],
        ),
    ]
